# NAME: ueransim-gnb
# LAST DEPLOYED: Fri Jul 26 07:43:23 2024
# NAMESPACE: open5gs
# STATUS: pending-install
# REVISION: 1
# TEST SUITE: None
# HOOKS:
# MANIFEST:
---
# Source: ueransim-ues/templates/ue-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-ueransim-ues-3
  namespace: "open5gs"
  labels:
    app.kubernetes.io/name: ueransim-ues-3
    helm.sh/chart: ueransim-ues-0.1.0
    app.kubernetes.io/instance: ueransim-gnb-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ues
data:
  ue.yaml: |
    # IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
    
    supi: 'imsi-999700000001301'
    mcc: '999'
    mnc: '70'
    
    # Permanent subscription key
    key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
    # Operator code (OP or OPC) of the UE
    op: 'E8ED289DEBA952E4283B54E88E6183CA'
    # This value specifies the OP type and it can be either 'OP' or 'OPC'
    opType: 'OPC'
    # Authentication Management Field (AMF) value
    amf: '8000'
    # IMEI number of the device. It is used if no SUPI is provided
    imei: '356938035643803'
    # IMEISV number of the device. It is used if no SUPI and IMEI is provided
    imeiSv: '4370816125816151'
    
    # List of gNB IP addresses for Radio Link Simulation
    gnbSearchList:
      - ${GNB_IP}
    
      # UAC Access Identities Configuration
    uacAic:
      mps: false
      mcs: false
    
    # UAC Access Control Class
    uacAcc:
      normalClass: 0
      class11: false
      class12: false
      class13: false
      class14: false
      class15: false
      
    # Initial PDU sessions to be established
    sessions:
      -
        apn: internet
        emergency: false
        slice:
          # sd: "0x111111"
          sst: 1
        type: IPv4
    
    # Configured NSSAI for this UE by HPLMN
    configured-nssai:
      - sst: 1
        # sd: 0x111111
    
    # Default Configured NSSAI for this UE
    default-nssai:
      - sst: 1
        # sd: 0x111111
    
    # Supported encryption algorithms by this UE
    integrity:
      IA1: true
      IA2: true
      IA3: true
    
    # Supported integrity algorithms by this UE
    ciphering:
      EA1: true
      EA2: true
      EA3: true
    
    # Integrity protection maximum data rate for user plane
    integrityMaxRate:
      uplink: 'full'
      downlink: 'full'
---
# Source: ueransim-ues/templates/ues-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb-ueransim-ues-3
  namespace: "open5gs"
  labels:
    app.kubernetes.io/name: ueransim-ues-3
    helm.sh/chart: ueransim-ues-0.1.0
    app.kubernetes.io/instance: ueransim-gnb-2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ues
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: ueransim-ues-3
      app.kubernetes.io/instance: ueransim-gnb-2
      app.kubernetes.io/component: ues
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ueransim-ues-3
        helm.sh/chart: ueransim-ues-0.1.0
        app.kubernetes.io/instance: ueransim-gnb-2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: ues
    spec:
      
      containers:
        - name: ues
          image: docker.io/openverso/ueransim:3.2.6
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: GNB_HOSTNAME
              value: ueransim-gnb-2
          args:
            - ue
            - -n
            - "3"
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: config
              mountPath: /etc/ueransim/ue.yaml
              subPath: "ue.yaml"
      volumes:
        - name: config
          configMap:
            name: ueransim-gnb-ueransim-ues-3
              # 
              # NOTES:
              # ueransim-ues successfully installed!
              # Check ues log with:
              # 
              # ```
              # kubectl -n open5gs logs deployment/ueransim-gnb-ueransim-ues
              # ```
              # 
              # You can enter ues terminal with:
              # 
              # ```
              # kubectl -n open5gs exec -ti deployment/ueransim-gnb-ueransim-ues-ues -- /bin/bash
              # ```
              # There is a tun interface for each ue. 
              # You can bind your application to the interface to test ue connectivity.
              # Example:
              # 
              # ```
              # ping -I uesimtun0 gradiant.org
              # traceroute -i uesimtun0 gradiant.org
              # curl --interface uesimtun0 https://www.gradiant.org/ 
              # ```
