# NAME: ueransim-gnb
# LAST DEPLOYED: Fri Jul 26 07:36:43 2024
# NAMESPACE: open5gs
# STATUS: pending-install
# REVISION: 1
# TEST SUITE: None
# HOOKS:
# MANIFEST:
---
# Source: ueransim-gnb/templates/gnb-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-gnb-3
  namespace: "open5gs"
  labels:
    app.kubernetes.io/name: ueransim-gnb-3
    helm.sh/chart: ueransim-gnb-0.2.4
    app.kubernetes.io/instance: ueransim-gnb-3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gnb
data:
  gnb.yaml: |
    mcc: 999 # Mobile Country Code value
    mnc: 70 # Mobile Network Code value (2 or 3 digits)
    
    nci: '0x0000000300'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 0001             # Tracking Area Code
    
    linkIp: ${RADIO_BIND_IP}   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: ${N2_BIND_IP}  # gNB's local IP address for N2 Interface (Usually same with local IP)
    gtpIp: ${N3_BIND_IP}   # gNB's local IP address for N3 Interface (Usually same with local IP)
    
    # List of AMF address information
    amfConfigs:
      - address: ${AMF_IP}
        port: 38412
    
    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1
        # sd: 0x111111
    
    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
---
# Source: ueransim-gnb/templates/gnb-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ueransim-gnb-3
  labels:
    app.kubernetes.io/name: ueransim-gnb-3
    helm.sh/chart: ueransim-gnb-0.2.4
    app.kubernetes.io/instance: ueransim-gnb-3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gnb
spec:
  ports:
  - name: gnb-ue
    port: 4997
    protocol: UDP
  - name: gnb-upf
    port: 2152
    protocol: UDP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: ueransim-gnb-3
    app.kubernetes.io/instance: ueransim-gnb-3
    app.kubernetes.io/component: gnb
---
# Source: ueransim-gnb/templates/gnb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb-3
  namespace: "open5gs"
  labels:
    app.kubernetes.io/name: ueransim-gnb-3
    helm.sh/chart: ueransim-gnb-0.2.4
    app.kubernetes.io/instance: ueransim-gnb-3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gnb
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: ueransim-gnb-3
      app.kubernetes.io/instance: ueransim-gnb-3
      app.kubernetes.io/component: gnb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ueransim-gnb-3
        helm.sh/chart: ueransim-gnb-0.2.4
        app.kubernetes.io/instance: ueransim-gnb-3
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: gnb
    spec:
      
      containers:
        - name: gnodeb
          image: docker.io/openverso/ueransim:3.2.6
          imagePullPolicy: Always
          args:
            - gnb
          ports:
          - name: gnb-ue
            containerPort: 4997
            protocol: UDP
          - name: gnb-upf
            containerPort: 2152
            protocol: UDP
          env:
            - name: AMF_HOSTNAME
              value: open5gs-amf-ngap
            - name: N2_IFACE
              value: eth0
            - name: N3_IFACE
              value: eth0
            - name: RADIO_IFACE
              value: eth0
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: config
              mountPath: /etc/ueransim/gnb.yaml
              subPath: "gnb.yaml"
      volumes:
        - name: config
          configMap:
            name: ueransim-gnb-3
---
# Source: ueransim-gnb/templates/gnb-hpa.yaml
#Autoscaler to limit gnb to 1.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ueransim-gnb-3
spec:
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: ueransim-gnb-3
      # 
      # NOTES:
      # ueransim-gnb successfully installed!
      # Check gnodeb log with:
      # 
      # ```
      # kubectl -n open5gs logs deployment/ueransim-gnb
      # ```
      # 
      # ---
      # 
      # No embedded ues where deployed.
      # 
      # You can deploy ues connected to this gnodeb with openverso/ueransim-ues chart:
      # 
      # ```
      # helm install -n open5gs ueransim-ues openverso/ueransim-ues --set gnb.hostname=ueransim-gnb
      # ```
